services:
  app:
    container_name: frontend
    # Build the Docker image using the Dockerfile in the current directory
    build:
      context: .

    # Map port 80 in the container to port 3000 on the host machine
    ports:
      - "80:80"
      - "443:443"

    # Load environment variables from the .env file
    env_file:
      - .env
