services:
  app:
    container_name: frontend
    # Build the Docker image using the Dockerfile in the current directory
    build:
      context: .

    # Map port 80 in the container to port 3000 on the host machine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

    # Load environment variables from the .env file
    env_file:
      - .env

  backend:
    container_name: backend
    build:
      context: ./backend  # Adjust path as needed
    environment:
      DATABASE_NAME: home_dashboard
      DATABASE_USER: user
      DATABASE_PASS: pass
      DATABASE_URI: mongodb://user:pass@mongodb:27017/home_dashboard?authSource=admin
    expose:
      - '3000'
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGODB_DATABASE=home_dashboard
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
